set -g mouse on
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel


set -s extended-keys on
set -g extended-keys-format csi-u
set -as terminal-features 'xterm\*:extkeys'

set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:RGB"
set -sg escape-time 0
set -g history-limit 50000
set -g renumber-windows on

set -g pane-border-format " #{pane_index}: #S "

set -g set-titles on
set -g set-titles-string "#S"

bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Splitting (using current pane's directory)
bind | split-window -h -c "#{pane_current_path}"  # Side by side
bind - split-window -v -c "#{pane_current_path}"  # Top and bottom
unbind '"'
unbind %

# Resize panes (no prefix needed — Ctrl+Alt+Arrow)
bind -n C-M-Left resize-pane -L 5
bind -n C-M-Right resize-pane -R 5
bind -n C-M-Up resize-pane -U 3
bind -n C-M-Down resize-pane -D 3

